name: core_data
description: Core data services like preferences and secure storage.
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  supabase_flutter: ^2.5.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  core_database:
    path: ../core_database
  intl: ^0.20.2

dev_dependencies:
  supabase_flutter: ^2.5.4
  flutter_test:
    sdk: flutter