name: feature_accounts
description: Manages accounts, classifications, and account-related UI.
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  supabase_flutter: ^2.5.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  drift: ^2.29.0
  collection: ^1.19.1 # Dependency for filtered_accounts_list_page.dart
  
  # Local Dependencies
  core_database:
    path: ../../core/core_database
  core_l10n:
    path: ../../core/core_l10n
  core_ui:
    path: ../../core/core_ui
  core_data:
    path: ../../core/core_data
  shared_services:
    path: ../../shared/shared_services
  shared_ui:
    path: ../../shared/shared_ui
  intl: ^0.20.2

  # Feature Dependencies
  feature_reports:
    path: ../feature_reports
  feature_transactions:
    path: ../feature_transactions

dev_dependencies:
  supabase_flutter: ^2.5.4
  flutter_test:
    sdk: flutter