name: mizan_monorepo
repository: https://github.com/your_org/mizan_monorepo

packages:
  - apps/**
  - packages/**

# CRITICAL FIX: Ensure pubspec_overrides are used for local linking
command:
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: false # Safer for initial setup

scripts:
  postbootstrap:
    run: dart pub global activate flutter_gen
    description: Activate code generators after bootstrap.

  build:all:
    run: |
      melos exec -c 1 -- \
        "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run build_runner in all packages.

  test:all:
    run: melos exec -- flutter test
    description: Run all tests.